server:
  port: 8080

spring:
  application:
    name: Ticketing Project - REST
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cybertek
    username: postgres
    password: 5432
    driver-class-name: org.postgresql.Driver
  sql:
    init:
#      mode: always
      data-locations: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    username: cybertekschool.email@gmail.com
    password: Cybertekschool@2020

security:
  jwt:
    secret-key: cybertek

springdoc:
  swagger-ui:
    path: /swagger-ui.html